version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        update-types:
        - "patch"
        - "minor"
      npm-major:
        applies-to: version-updates
        update-types:
        - "major"
  - package-ecosystem: "cargo"
    directories: 
      - "/"
      - "/core"
      - "/soroflare-wrangler"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 2
    groups:
      cargo-minor-and-patch:
        applies-to: version-updates
        update-types:
        - "patch"
        - "minor"
      cargo-major:
        applies-to: version-updates
        update-types:
        - "major"